# Generated by Django 5.1.7 on 2025-03-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecturer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="passport",
            field=models.ImageField(
                blank=True, null=True, upload_to="lecturer_passports/"
            ),
        ),
    ]
