name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py migrate --noinput

    - name: Collect Static Files
      run: |
        python manage.py collectstatic --noinput

    - name: Create Superuser
      env:
        DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      run: |
        python manage.py createsuperuser \
          --noinput \
          --username $DJANGO_SUPERUSER_USERNAME \
          --email $DJANGO_SUPERUSER_EMAIL || true

